/* person_mask.effect — the compositing half of the Cutout filter, in libobs'
 * effect dialect (HLSL-shaped; libobs transpiles it for Metal, OpenGL and
 * D3D11). Embedded as a string so the filter never has to find a data
 * directory: the shim has no module path of its own.
 *
 * Techniques
 *   Blur  one separable gaussian tap line along `blur_dir` (set to
 *         (1/w, 0) then (0, 1/h) for the two passes; `blur_radius` scales it)
 *   Cut   alpha = processed mask; output premultiplied
 *   Soft  lerp(blurred, sharp, processed mask)
 *
 * Mask processing (shared): erosion is a min over a ring of samples
 * `erode` mask-texels out (hair fringes and halo go first); feather widens
 * the 0.5 threshold into a smoothstep band.
 */
#ifndef PRODUCER_PERSON_MASK_EFFECT_H
#define PRODUCER_PERSON_MASK_EFFECT_H

static const char PRODUCER_PERSON_MASK_EFFECT[] =
	"uniform float4x4 ViewProj;\n"
	"uniform texture2d image;\n"
	"uniform texture2d mask;\n"
	"uniform texture2d blurred;\n"
	"uniform float2 blur_dir;\n"
	"uniform float2 mask_texel;\n"
	"uniform float feather;\n"
	"uniform float erode;\n"
	"\n"
	"sampler_state linearSampler {\n"
	"	Filter    = Linear;\n"
	"	AddressU  = Clamp;\n"
	"	AddressV  = Clamp;\n"
	"};\n"
	"\n"
	"struct VertData {\n"
	"	float4 pos : POSITION;\n"
	"	float2 uv  : TEXCOORD0;\n"
	"};\n"
	"\n"
	"VertData VSDefault(VertData v_in)\n"
	"{\n"
	"	VertData vert_out;\n"
	"	vert_out.pos = mul(float4(v_in.pos.xyz, 1.0), ViewProj);\n"
	"	vert_out.uv  = v_in.uv;\n"
	"	return vert_out;\n"
	"}\n"
	"\n"
	"float MaskAt(float2 uv)\n"
	"{\n"
	"	return mask.Sample(linearSampler, uv).r;\n"
	"}\n"
	"\n"
	"float ProcessedMask(float2 uv)\n"
	"{\n"
	"	float m = MaskAt(uv);\n"
	"	float2 r = mask_texel * erode;\n"
	"	m = min(m, MaskAt(uv + float2( r.x, 0.0)));\n"
	"	m = min(m, MaskAt(uv + float2(-r.x, 0.0)));\n"
	"	m = min(m, MaskAt(uv + float2(0.0,  r.y)));\n"
	"	m = min(m, MaskAt(uv + float2(0.0, -r.y)));\n"
	"	m = min(m, MaskAt(uv + float2( r.x,  r.y) * 0.7071));\n"
	"	m = min(m, MaskAt(uv + float2(-r.x,  r.y) * 0.7071));\n"
	"	m = min(m, MaskAt(uv + float2( r.x, -r.y) * 0.7071));\n"
	"	m = min(m, MaskAt(uv + float2(-r.x, -r.y) * 0.7071));\n"
	"	float half_band = max(feather, 0.02) * 0.5;\n"
	"	return smoothstep(0.5 - half_band, 0.5 + half_band, m);\n"
	"}\n"
	"\n"
	"float4 PSBlur(VertData v_in) : TARGET\n"
	"{\n"
	"	float4 sum = image.Sample(linearSampler, v_in.uv) * 0.2270270270;\n"
	"	float2 o1 = blur_dir * 1.3846153846;\n"
	"	float2 o2 = blur_dir * 3.2307692308;\n"
	"	sum += image.Sample(linearSampler, v_in.uv + o1) * 0.3162162162;\n"
	"	sum += image.Sample(linearSampler, v_in.uv - o1) * 0.3162162162;\n"
	"	sum += image.Sample(linearSampler, v_in.uv + o2) * 0.0702702703;\n"
	"	sum += image.Sample(linearSampler, v_in.uv - o2) * 0.0702702703;\n"
	"	return sum;\n"
	"}\n"
	"\n"
	"float4 PSCut(VertData v_in) : TARGET\n"
	"{\n"
	"	float4 rgba = image.Sample(linearSampler, v_in.uv);\n"
	"	return rgba * ProcessedMask(v_in.uv);\n"
	"}\n"
	"\n"
	"float4 PSSoft(VertData v_in) : TARGET\n"
	"{\n"
	"	float4 sharp = image.Sample(linearSampler, v_in.uv);\n"
	"	float4 soft  = blurred.Sample(linearSampler, v_in.uv);\n"
	"	return lerp(soft, sharp, ProcessedMask(v_in.uv));\n"
	"}\n"
	"\n"
	"technique Blur\n"
	"{\n"
	"	pass\n"
	"	{\n"
	"		vertex_shader = VSDefault(v_in);\n"
	"		pixel_shader  = PSBlur(v_in);\n"
	"	}\n"
	"}\n"
	"\n"
	"technique Cut\n"
	"{\n"
	"	pass\n"
	"	{\n"
	"		vertex_shader = VSDefault(v_in);\n"
	"		pixel_shader  = PSCut(v_in);\n"
	"	}\n"
	"}\n"
	"\n"
	"technique Soft\n"
	"{\n"
	"	pass\n"
	"	{\n"
	"		vertex_shader = VSDefault(v_in);\n"
	"		pixel_shader  = PSSoft(v_in);\n"
	"	}\n"
	"}\n";

#endif /* PRODUCER_PERSON_MASK_EFFECT_H */
