/* person_mask.effect — the compositing half of the Cutout filter, in libobs'
 * effect dialect (HLSL-shaped; libobs transpiles it for Metal, OpenGL and
 * D3D11). Embedded as a string so the filter never has to find a data
 * directory: the shim has no module path of its own.
 *
 * Techniques
 *   Blur  one separable gaussian tap line along `blur_dir` (set to
 *         (1/w, 0) then (0, 1/h) for the two passes; `blur_radius` scales it)
 *   Cut   alpha = processed mask; output premultiplied
 *   Soft  lerp(blurred, sharp, processed mask)
 *   Refine  color-guided mask upsampling; stores linear confidence data.
 *
 * Mask processing (shared): erosion is a min over a ring of samples
 * `erode` mask-texels out (hair fringes and halo go first); feather widens
 * the 0.5 threshold into a smoothstep band.
 */
#ifndef PRODUCER_PERSON_MASK_EFFECT_H
#define PRODUCER_PERSON_MASK_EFFECT_H

static const char PRODUCER_PERSON_MASK_EFFECT[] =
	"uniform float4x4 ViewProj;\n"
	"uniform texture2d image;\n"
	"uniform texture2d mask;\n"
	"uniform texture2d blurred;\n"
	"uniform float2 blur_dir;\n"
	"uniform float2 mask_texel;\n"
	"uniform float2 refine_texel;\n"
	"uniform float edge_refine;\n"
	"uniform float feather;\n"
	"uniform float erode;\n"
	"\n"
	"sampler_state linearSampler {\n"
	"\tFilter    = Linear;\n"
	"\tAddressU  = Clamp;\n"
	"\tAddressV  = Clamp;\n"
	"};\n"
	"\n"
	"struct VertData {\n"
	"\tfloat4 pos : POSITION;\n"
	"\tfloat2 uv  : TEXCOORD0;\n"
	"};\n"
	"\n"
	"VertData VSDefault(VertData v_in)\n"
	"{\n"
	"\tVertData vert_out;\n"
	"\tvert_out.pos = mul(float4(v_in.pos.xyz, 1.0), ViewProj);\n"
	"\tvert_out.uv  = v_in.uv;\n"
	"\treturn vert_out;\n"
	"}\n"
	"\n"
	"float MaskAt(float2 uv)\n"
	"{\n"
	"\treturn mask.Sample(linearSampler, uv).r;\n"
	"}\n"
	"\n"
	"float ProcessedMask(float2 uv)\n"
	"{\n"
	"\tfloat m = MaskAt(uv);\n"
	"\tfloat2 r = lerp(mask_texel, refine_texel, edge_refine) * erode;\n"
	"\tm = min(m, MaskAt(uv + float2( r.x, 0.0)));\n"
	"\tm = min(m, MaskAt(uv + float2(-r.x, 0.0)));\n"
	"\tm = min(m, MaskAt(uv + float2(0.0,  r.y)));\n"
	"\tm = min(m, MaskAt(uv + float2(0.0, -r.y)));\n"
	"\tm = min(m, MaskAt(uv + float2( r.x,  r.y) * 0.7071));\n"
	"\tm = min(m, MaskAt(uv + float2(-r.x,  r.y) * 0.7071));\n"
	"\tm = min(m, MaskAt(uv + float2( r.x, -r.y) * 0.7071));\n"
	"\tm = min(m, MaskAt(uv + float2(-r.x, -r.y) * 0.7071));\n"
	"\tfloat half_band = max(feather, 0.02) * 0.5;\n"
	"\treturn smoothstep(0.5 - half_band, 0.5 + half_band, m);\n"
	"}\n"
	"\n"
	"float2 GuidedTap(float2 uv, float2 offset, float3 center, float spatial)\n"
	"{\n"
	"\tfloat2 sample_uv = uv + offset;\n"
	"\tfloat3 delta = image.Sample(linearSampler, sample_uv).rgb - center;\n"
	"\tfloat weight = spatial / (1.0 + 80.0 * dot(delta, delta));\n"
	"\treturn float2(MaskAt(sample_uv) * weight, weight);\n"
	"}\n"
	"\n"
	"float4 PSRefine(VertData v_in) : TARGET\n"
	"{\n"
	"\tfloat2 uv = v_in.uv;\n"
	"\tfloat3 center = image.Sample(linearSampler, uv).rgb;\n"
	"\tfloat m = MaskAt(uv);\n"
	"\tfloat2 sum = float2(m, 1.0);\n"
	"\tfloat2 r = mask_texel;\n"
	"\tsum += GuidedTap(uv, float2( r.x, 0.0), center, 0.65);\n"
	"\tsum += GuidedTap(uv, float2(-r.x, 0.0), center, 0.65);\n"
	"\tsum += GuidedTap(uv, float2(0.0,  r.y), center, 0.65);\n"
	"\tsum += GuidedTap(uv, float2(0.0, -r.y), center, 0.65);\n"
	"\tsum += GuidedTap(uv, float2( r.x,  r.y), center, 0.40);\n"
	"\tsum += GuidedTap(uv, float2(-r.x,  r.y), center, 0.40);\n"
	"\tsum += GuidedTap(uv, float2( r.x, -r.y), center, 0.40);\n"
	"\tsum += GuidedTap(uv, float2(-r.x, -r.y), center, 0.40);\n"
	"\tfloat refined = lerp(m, sum.x / sum.y, edge_refine);\n"
	"\treturn float4(refined, refined, refined, 1.0);\n"
	"}\n"
	"\n"
	"float4 PSBlur(VertData v_in) : TARGET\n"
	"{\n"
	"\tfloat4 sum = image.Sample(linearSampler, v_in.uv) * 0.2270270270;\n"
	"\tfloat2 o1 = blur_dir * 1.3846153846;\n"
	"\tfloat2 o2 = blur_dir * 3.2307692308;\n"
	"\tsum += image.Sample(linearSampler, v_in.uv + o1) * 0.3162162162;\n"
	"\tsum += image.Sample(linearSampler, v_in.uv - o1) * 0.3162162162;\n"
	"\tsum += image.Sample(linearSampler, v_in.uv + o2) * 0.0702702703;\n"
	"\tsum += image.Sample(linearSampler, v_in.uv - o2) * 0.0702702703;\n"
	"\treturn sum;\n"
	"}\n"
	"\n"
	"float4 PSCut(VertData v_in) : TARGET\n"
	"{\n"
	"\tfloat4 rgba = image.Sample(linearSampler, v_in.uv);\n"
	"\treturn rgba * ProcessedMask(v_in.uv);\n"
	"}\n"
	"\n"
	"float4 PSSoft(VertData v_in) : TARGET\n"
	"{\n"
	"\tfloat4 sharp = image.Sample(linearSampler, v_in.uv);\n"
	"\tfloat4 soft  = blurred.Sample(linearSampler, v_in.uv);\n"
	"\treturn lerp(soft, sharp, ProcessedMask(v_in.uv));\n"
	"}\n"
	"\n"
	"technique Blur\n"
	"{\n"
	"\tpass\n"
	"\t{\n"
	"\t\tvertex_shader = VSDefault(v_in);\n"
	"\t\tpixel_shader  = PSBlur(v_in);\n"
	"\t}\n"
	"}\n"
	"\n"
	"technique Refine\n"
	"{\n"
	"\tpass\n"
	"\t{\n"
	"\t\tvertex_shader = VSDefault(v_in);\n"
	"\t\tpixel_shader  = PSRefine(v_in);\n"
	"\t}\n"
	"}\n"
	"\n"
	"technique Cut\n"
	"{\n"
	"\tpass\n"
	"\t{\n"
	"\t\tvertex_shader = VSDefault(v_in);\n"
	"\t\tpixel_shader  = PSCut(v_in);\n"
	"\t}\n"
	"}\n"
	"\n"
	"technique Soft\n"
	"{\n"
	"\tpass\n"
	"\t{\n"
	"\t\tvertex_shader = VSDefault(v_in);\n"
	"\t\tpixel_shader  = PSSoft(v_in);\n"
	"\t}\n"
	"}\n";

#endif /* PRODUCER_PERSON_MASK_EFFECT_H */
