import {useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {importAsset,PACKAGE_BYTES} from './assets';
import {parsePackage,type PresentationPackage} from './schema';
export function MediaAssetsDialog({doc,layoutId,onLoad,onClose}:{doc:PresentationPackage;layoutId:string;onLoad:(doc:PresentationPackage)=>void;onClose:()=>void}){
 const ref=useRef<HTMLDialogElement>(null),file=useRef<HTMLInputElement>(null);const [error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close();},[]);
 const save=(next:PresentationPackage)=>{onLoad(parsePackage(next));};
 const add=async(files:FileList|null)=>{if(!files)return;setBusy(true);setError('');try{const next=structuredClone(doc);next.set.assets??={};for(const file of Array.from(files)){const asset=await importAsset(file);let id=file.name.replace(/\.[^.]+$/,'').replace(/[^a-zA-Z0-9_-]/g,'-').slice(0,35);if(!/^[a-zA-Z]/.test(id))id='asset-'+id;let key=id,n=2;while(next.set.assets[key])key=id+'-'+n++;next.set.assets[key]=asset;}save(next);}catch(e){setError(String(e));}finally{setBusy(false);if(file.current)file.current.value='';}};
 const place=(assetId:string)=>{try{const next=structuredClone(doc),layout=next.set.layouts.find(l=>l.id===layoutId)??next.set.layouts[0];if(layout.root.type!=='box')throw new Error('This layout needs a box root to place media.');layout.root.children??=[];layout.root.children.push({id:'media-'+crypto.randomUUID().slice(0,8),type:'media',assetId,fit:'contain',loop:true,autoplay:true,styles:{position:'absolute',left:layout.width*.1,top:layout.height*.1,width:layout.width*.4,height:layout.height*.4}});save(next);}catch(e){setError(String(e));}};
 const remove=(id:string)=>{try{const next=structuredClone(doc);delete next.set.assets?.[id];save(next);}catch{setError('This asset is used in a layout. Remove its media nodes with your agent before deleting the file.');}};
 const download=()=>{const blob=new Blob([JSON.stringify(doc,null,2)],{type:'application/json'});if(blob.size>PACKAGE_BYTES){setError('Package exceeds 40 MB.');return;}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=doc.id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return createPortal(<dialog ref={ref} className="set-authoring-dialog set-media-dialog" aria-label="Set media assets" onCancel={onClose}><header><strong>Media assets</strong><button onClick={onClose}>Close</button></header><p>Embedded files travel inside the exported JSON. For full-length clips, use Load media in the reaction player to link a local file. Place an asset in the current layout, then ask your agent to adjust its size and position. Video is muted.</p><div className="set-authoring-actions"><button disabled={busy} onClick={()=>file.current?.click()}>{busy?'Importing…':'Import media'}</button><button onClick={download}>Download package with assets</button></div><input ref={file} hidden type="file" multiple accept="image/png,image/jpeg,image/webp,image/gif,video/mp4,video/webm,.json" aria-label="Import media assets" onChange={e=>void add(e.target.files)}/>{error&&<p role="alert">{error}</p>}<ul className="set-media-list">{Object.entries(doc.set.assets??{}).map(([id,asset])=><li key={id}><div><strong>{asset.name}</strong><small>{id} · {asset.mime} · {asset.data.startsWith('producer-media:')?'Linked local file':`${Math.round(asset.data.length*.75/1024)} KB`}</small></div><button onClick={()=>place(id)}>Place in layout</button><button onClick={()=>remove(id)}>Remove</button></li>)}</ul>{!Object.keys(doc.set.assets??{}).length&&<p>No assets yet. Import PNG, JPEG, WebP, GIF, MP4, WebM or self-contained Lottie JSON.</p>}<footer>Embedded imports: 12 MB per file · 40 MB per package. Linked local clips have no embedded upload limit.</footer></dialog>,document.body);
}
